// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgReq struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Pic                  []byte               `protobuf:"bytes,2,opt,name=pic,proto3" json:"pic,omitempty"`
	ParentId             string               `protobuf:"bytes,3,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Topic                string               `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	TimeName             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time_name,json=timeName,proto3" json:"time_name,omitempty"`
	Status               Status               `protobuf:"varint,6,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	Uuid                 string               `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgReq) Reset()         { *m = MsgReq{} }
func (m *MsgReq) String() string { return proto.CompactTextString(m) }
func (*MsgReq) ProtoMessage()    {}
func (*MsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReq.Unmarshal(m, b)
}
func (m *MsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReq.Marshal(b, m, deterministic)
}
func (m *MsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReq.Merge(m, src)
}
func (m *MsgReq) XXX_Size() int {
	return xxx_messageInfo_MsgReq.Size(m)
}
func (m *MsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReq proto.InternalMessageInfo

func (m *MsgReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MsgReq) GetPic() []byte {
	if m != nil {
		return m.Pic
	}
	return nil
}

func (m *MsgReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *MsgReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MsgReq) GetTimeName() *timestamp.Timestamp {
	if m != nil {
		return m.TimeName
	}
	return nil
}

func (m *MsgReq) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

func (m *MsgReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type MsgResp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResp) Reset()         { *m = MsgResp{} }
func (m *MsgResp) String() string { return proto.CompactTextString(m) }
func (*MsgResp) ProtoMessage()    {}
func (*MsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResp.Unmarshal(m, b)
}
func (m *MsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResp.Marshal(b, m, deterministic)
}
func (m *MsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResp.Merge(m, src)
}
func (m *MsgResp) XXX_Size() int {
	return xxx_messageInfo_MsgResp.Size(m)
}
func (m *MsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResp proto.InternalMessageInfo

func (m *MsgResp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

func (m *MsgResp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgReq)(nil), "api.MsgReq")
	proto.RegisterType((*MsgResp)(nil), "api.MsgResp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x95, 0x9b, 0x36, 0x6d, 0xaf, 0x01, 0xa1, 0x13, 0x83, 0x95, 0x85, 0xa8, 0x30, 0x44, 0x42,
	0x72, 0x51, 0x18, 0xd8, 0xd9, 0x18, 0xca, 0x10, 0xd8, 0x91, 0x4b, 0x4d, 0x64, 0x09, 0xd7, 0xa6,
	0x3e, 0x4b, 0x7c, 0x27, 0x5f, 0x84, 0x6c, 0x53, 0xca, 0xc6, 0xf6, 0xde, 0xdd, 0xf3, 0xf3, 0x7b,
	0x07, 0x27, 0x46, 0x79, 0x2f, 0x07, 0x25, 0xdc, 0xde, 0x92, 0xc5, 0x42, 0x3a, 0x5d, 0x57, 0x9e,
	0x24, 0x05, 0x9f, 0x47, 0xf5, 0xc5, 0x60, 0xed, 0xf0, 0xae, 0x56, 0x89, 0x6d, 0xc2, 0xdb, 0x8a,
	0xb4, 0x51, 0x9e, 0xa4, 0x71, 0x59, 0xb0, 0xfc, 0x62, 0x50, 0xae, 0xfd, 0xd0, 0xab, 0x0f, 0x44,
	0x18, 0x93, 0xfa, 0x24, 0xce, 0x1a, 0xd6, 0xce, 0xfb, 0x84, 0xf1, 0x0c, 0x0a, 0xa7, 0x5f, 0xf9,
	0xa8, 0x61, 0x6d, 0xd5, 0x47, 0x88, 0x35, 0xcc, 0x9c, 0xdc, 0xab, 0x1d, 0x3d, 0x6c, 0x79, 0x91,
	0x94, 0xbf, 0x1c, 0xcf, 0x61, 0x42, 0x36, 0xea, 0xc7, 0x69, 0x91, 0x09, 0xde, 0xc1, 0x3c, 0xfe,
	0xfa, 0xb2, 0x93, 0x46, 0xf1, 0x49, 0xc3, 0xda, 0x45, 0x57, 0x8b, 0x9c, 0x4b, 0x1c, 0x72, 0x89,
	0xe7, 0x43, 0xae, 0x7e, 0x16, 0xc5, 0x8f, 0xd2, 0x28, 0xbc, 0x84, 0x32, 0x97, 0xe1, 0x65, 0xc3,
	0xda, 0xd3, 0x6e, 0x21, 0xa4, 0xd3, 0xe2, 0x29, 0x8d, 0xfa, 0x9f, 0x55, 0x4c, 0x1d, 0x82, 0xde,
	0xf2, 0x69, 0x4e, 0x1d, 0xf1, 0xf2, 0x1e, 0xa6, 0xa9, 0x93, 0x77, 0x7f, 0x3c, 0xd8, 0xff, 0x1e,
	0xa3, 0xa3, 0x47, 0x77, 0x0d, 0xc5, 0xda, 0x0f, 0x78, 0x05, 0x85, 0x0b, 0x84, 0xf9, 0x59, 0x3e,
	0x54, 0x5d, 0x1d, 0x89, 0x77, 0x2d, 0xbb, 0x61, 0x9b, 0x32, 0xf5, 0xb8, 0xfd, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x7d, 0xce, 0xad, 0x58, 0x91, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Put(ctx context.Context, opts ...grpc.CallOption) (Msg_PutClient, error)
}

type msgClient struct {
	cc *grpc.ClientConn
}

func NewMsgClient(cc *grpc.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Put(ctx context.Context, opts ...grpc.CallOption) (Msg_PutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Msg_serviceDesc.Streams[0], "/api.Msg/put", opts...)
	if err != nil {
		return nil, err
	}
	x := &msgPutClient{stream}
	return x, nil
}

type Msg_PutClient interface {
	Send(*MsgReq) error
	Recv() (*MsgResp, error)
	grpc.ClientStream
}

type msgPutClient struct {
	grpc.ClientStream
}

func (x *msgPutClient) Send(m *MsgReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *msgPutClient) Recv() (*MsgResp, error) {
	m := new(MsgResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Put(Msg_PutServer) error
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Put(srv Msg_PutServer) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}

func RegisterMsgServer(s *grpc.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MsgServer).Put(&msgPutServer{stream})
}

type Msg_PutServer interface {
	Send(*MsgResp) error
	Recv() (*MsgReq, error)
	grpc.ServerStream
}

type msgPutServer struct {
	grpc.ServerStream
}

func (x *msgPutServer) Send(m *MsgResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *msgPutServer) Recv() (*MsgReq, error) {
	m := new(MsgReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "put",
			Handler:       _Msg_Put_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
