// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgReq struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 []string             `protobuf:"bytes,2,rep,name=text,proto3" json:"text,omitempty"`
	Pic                  [][]byte             `protobuf:"bytes,3,rep,name=pic,proto3" json:"pic,omitempty"`
	ParentId             string               `protobuf:"bytes,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Topic                string               `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	TimeName             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=time_name,json=timeName,proto3" json:"time_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MsgReq) Reset()         { *m = MsgReq{} }
func (m *MsgReq) String() string { return proto.CompactTextString(m) }
func (*MsgReq) ProtoMessage()    {}
func (*MsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReq.Unmarshal(m, b)
}
func (m *MsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReq.Marshal(b, m, deterministic)
}
func (m *MsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReq.Merge(m, src)
}
func (m *MsgReq) XXX_Size() int {
	return xxx_messageInfo_MsgReq.Size(m)
}
func (m *MsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReq proto.InternalMessageInfo

func (m *MsgReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgReq) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *MsgReq) GetPic() [][]byte {
	if m != nil {
		return m.Pic
	}
	return nil
}

func (m *MsgReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *MsgReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *MsgReq) GetTimeName() *timestamp.Timestamp {
	if m != nil {
		return m.TimeName
	}
	return nil
}

type MsgResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResp) Reset()         { *m = MsgResp{} }
func (m *MsgResp) String() string { return proto.CompactTextString(m) }
func (*MsgResp) ProtoMessage()    {}
func (*MsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResp.Unmarshal(m, b)
}
func (m *MsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResp.Marshal(b, m, deterministic)
}
func (m *MsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResp.Merge(m, src)
}
func (m *MsgResp) XXX_Size() int {
	return xxx_messageInfo_MsgResp.Size(m)
}
func (m *MsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResp proto.InternalMessageInfo

func (m *MsgResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgResp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

func init() {
	proto.RegisterType((*MsgReq)(nil), "api.MsgReq")
	proto.RegisterType((*MsgResp)(nil), "api.MsgResp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xe5, 0xa4, 0x49, 0x9b, 0x6b, 0xbe, 0xea, 0x93, 0xc5, 0x60, 0x65, 0x21, 0x2a, 0x12,
	0xf2, 0xe4, 0x42, 0x18, 0xd8, 0x58, 0x98, 0x18, 0xca, 0x60, 0xd8, 0x91, 0x4b, 0x4c, 0xb0, 0x84,
	0x6b, 0x13, 0x5f, 0x25, 0xfe, 0x12, 0xff, 0x12, 0xc5, 0xa6, 0x30, 0xb0, 0xdd, 0x7b, 0xef, 0x63,
	0xe9, 0xf1, 0xc1, 0x3f, 0xab, 0x43, 0x50, 0x83, 0x16, 0x7e, 0x74, 0xe8, 0x68, 0xae, 0xbc, 0x69,
	0xea, 0x80, 0x0a, 0x0f, 0x21, 0xad, 0x9a, 0xd3, 0xc1, 0xb9, 0xe1, 0x4d, 0x6f, 0x62, 0xda, 0x1d,
	0x5e, 0x36, 0x68, 0xac, 0x0e, 0xa8, 0xac, 0x4f, 0xc0, 0xfa, 0x93, 0x40, 0xb9, 0x0d, 0x83, 0xd4,
	0xef, 0x74, 0x05, 0x99, 0xe9, 0x19, 0x69, 0x09, 0xaf, 0x64, 0x66, 0x7a, 0x4a, 0x61, 0x86, 0xfa,
	0x03, 0x59, 0xd6, 0xe6, 0xbc, 0x92, 0x71, 0xa6, 0xff, 0x21, 0xf7, 0xe6, 0x99, 0xe5, 0x6d, 0xce,
	0x6b, 0x39, 0x8d, 0xb4, 0x81, 0x85, 0x57, 0xa3, 0xde, 0xe3, 0x5d, 0xcf, 0x66, 0xf1, 0xed, 0x4f,
	0xa6, 0x27, 0x50, 0xa0, 0x9b, 0xf8, 0x22, 0x16, 0x29, 0xd0, 0x6b, 0xa8, 0x26, 0x8b, 0xa7, 0xbd,
	0xb2, 0x9a, 0x95, 0x2d, 0xe1, 0xcb, 0xae, 0x11, 0xc9, 0x53, 0x1c, 0x3d, 0xc5, 0xe3, 0xd1, 0x53,
	0x2e, 0x26, 0xf8, 0x5e, 0x59, 0xbd, 0xbe, 0x81, 0x79, 0x54, 0x0d, 0xfe, 0x8f, 0xeb, 0x19, 0x94,
	0xe9, 0xdf, 0x2c, 0x6b, 0x09, 0x5f, 0x75, 0x4b, 0xa1, 0xbc, 0x11, 0x0f, 0x71, 0x25, 0xbf, 0xab,
	0xee, 0x12, 0xe6, 0x5b, 0xa5, 0x03, 0x8e, 0x8e, 0x9e, 0x43, 0x71, 0xfb, 0xaa, 0x10, 0x69, 0x02,
	0xd3, 0x05, 0x9a, 0xfa, 0x37, 0x04, 0xcf, 0xc9, 0x05, 0xd9, 0x95, 0x51, 0xe8, 0xea, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0xbe, 0xbe, 0xbd, 0x6a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MaestroClient is the client API for Maestro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MaestroClient interface {
	Chatt(ctx context.Context, opts ...grpc.CallOption) (Maestro_ChattClient, error)
}

type maestroClient struct {
	cc *grpc.ClientConn
}

func NewMaestroClient(cc *grpc.ClientConn) MaestroClient {
	return &maestroClient{cc}
}

func (c *maestroClient) Chatt(ctx context.Context, opts ...grpc.CallOption) (Maestro_ChattClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Maestro_serviceDesc.Streams[0], "/api.Maestro/Chatt", opts...)
	if err != nil {
		return nil, err
	}
	x := &maestroChattClient{stream}
	return x, nil
}

type Maestro_ChattClient interface {
	Send(*MsgReq) error
	Recv() (*MsgResp, error)
	grpc.ClientStream
}

type maestroChattClient struct {
	grpc.ClientStream
}

func (x *maestroChattClient) Send(m *MsgReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maestroChattClient) Recv() (*MsgResp, error) {
	m := new(MsgResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaestroServer is the server API for Maestro service.
type MaestroServer interface {
	Chatt(Maestro_ChattServer) error
}

// UnimplementedMaestroServer can be embedded to have forward compatible implementations.
type UnimplementedMaestroServer struct {
}

func (*UnimplementedMaestroServer) Chatt(srv Maestro_ChattServer) error {
	return status.Errorf(codes.Unimplemented, "method Chatt not implemented")
}

func RegisterMaestroServer(s *grpc.Server, srv MaestroServer) {
	s.RegisterService(&_Maestro_serviceDesc, srv)
}

func _Maestro_Chatt_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaestroServer).Chatt(&maestroChattServer{stream})
}

type Maestro_ChattServer interface {
	Send(*MsgResp) error
	Recv() (*MsgReq, error)
	grpc.ServerStream
}

type maestroChattServer struct {
	grpc.ServerStream
}

func (x *maestroChattServer) Send(m *MsgResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maestroChattServer) Recv() (*MsgReq, error) {
	m := new(MsgReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Maestro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Maestro",
	HandlerType: (*MaestroServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chatt",
			Handler:       _Maestro_Chatt_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
