// Code generated by protoc-gen-go. DO NOT EDIT.
// source: register.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	UserName             string               `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	PassWord             []byte               `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	FirstName            string               `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string               `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              *RegisterReq_Address `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Device               string               `protobuf:"bytes,8,opt,name=device,proto3" json:"device,omitempty"`
	TimeName             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=time_name,json=timeName,proto3" json:"time_name,omitempty"`
	AppName              string               `protobuf:"bytes,10,opt,name=AppName,proto3" json:"AppName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterReq) GetPassWord() []byte {
	if m != nil {
		return m.PassWord
	}
	return nil
}

func (m *RegisterReq) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterReq) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterReq) GetAddress() *RegisterReq_Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *RegisterReq) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *RegisterReq) GetTimeName() *timestamp.Timestamp {
	if m != nil {
		return m.TimeName
	}
	return nil
}

func (m *RegisterReq) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type RegisterReq_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq_Address) Reset()         { *m = RegisterReq_Address{} }
func (m *RegisterReq_Address) String() string { return proto.CompactTextString(m) }
func (*RegisterReq_Address) ProtoMessage()    {}
func (*RegisterReq_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{0, 0}
}

func (m *RegisterReq_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq_Address.Unmarshal(m, b)
}
func (m *RegisterReq_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq_Address.Marshal(b, m, deterministic)
}
func (m *RegisterReq_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq_Address.Merge(m, src)
}
func (m *RegisterReq_Address) XXX_Size() int {
	return xxx_messageInfo_RegisterReq_Address.Size(m)
}
func (m *RegisterReq_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq_Address.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq_Address proto.InternalMessageInfo

func (m *RegisterReq_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *RegisterReq_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *RegisterReq_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *RegisterReq_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1303fe8288f4efb6, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterReq)(nil), "api.RegisterReq")
	proto.RegisterType((*RegisterReq_Address)(nil), "api.RegisterReq.Address")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("register.proto", fileDescriptor_1303fe8288f4efb6) }

var fileDescriptor_1303fe8288f4efb6 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0xd9, 0xff, 0xb6, 0xdd, 0xdd, 0xe9, 0x1f, 0x29, 0x41, 0x24, 0x2c, 0x82, 0xa5, 0xa7,
	0x3d, 0x6d, 0xa1, 0x0a, 0x9e, 0x7b, 0xf0, 0xea, 0x21, 0x08, 0x9e, 0x44, 0xd2, 0xee, 0xb4, 0x06,
	0xba, 0xdd, 0x98, 0xa4, 0x42, 0xfd, 0x46, 0x7e, 0x4b, 0xc9, 0x64, 0xd3, 0x16, 0x6f, 0xf3, 0x66,
	0xe6, 0x4d, 0xf2, 0x7e, 0x70, 0x65, 0x70, 0xab, 0xac, 0x43, 0x53, 0x6b, 0xd3, 0xb9, 0x8e, 0xa5,
	0x52, 0xab, 0xf2, 0x6e, 0xdb, 0x75, 0xdb, 0x1d, 0xce, 0xa9, 0xb5, 0x3a, 0x6c, 0xe6, 0x4e, 0xb5,
	0x68, 0x9d, 0x6c, 0x75, 0xd8, 0x9a, 0xfd, 0xa4, 0x30, 0x16, 0xbd, 0x51, 0xe0, 0x27, 0x2b, 0x21,
	0x3f, 0x58, 0x34, 0xcf, 0xb2, 0x45, 0x9e, 0x4c, 0x93, 0xaa, 0x10, 0x27, 0xed, 0x67, 0x5a, 0x5a,
	0xfb, 0xda, 0x99, 0x86, 0xff, 0x9b, 0x26, 0xd5, 0x7f, 0x71, 0xd2, 0xec, 0x16, 0x8a, 0x8d, 0x32,
	0xd6, 0x91, 0x31, 0x25, 0xe3, 0xb9, 0xe1, 0x9d, 0x3b, 0xd9, 0x0f, 0x07, 0xe1, 0x6a, 0xd4, 0xec,
	0x1a, 0x86, 0xd8, 0x4a, 0xb5, 0xe3, 0x43, 0x1a, 0x04, 0xe1, 0xbb, 0xfa, 0xa3, 0xdb, 0x23, 0x1f,
	0x85, 0x2e, 0x09, 0xb6, 0x80, 0x4c, 0x36, 0x8d, 0x41, 0x6b, 0x79, 0x36, 0x4d, 0xaa, 0xf1, 0x82,
	0xd7, 0x52, 0xab, 0xfa, 0x22, 0x40, 0xbd, 0x0c, 0x73, 0x11, 0x17, 0xd9, 0x0d, 0x8c, 0x1a, 0xfc,
	0x52, 0x6b, 0xe4, 0x39, 0x9d, 0xea, 0x15, 0x7b, 0x84, 0xc2, 0xc3, 0x78, 0xdf, 0xfb, 0x4f, 0x15,
	0x74, 0xad, 0xac, 0x03, 0xae, 0x3a, 0xe2, 0xaa, 0x5f, 0x22, 0x2e, 0x91, 0xfb, 0x65, 0xfa, 0x30,
	0x87, 0x6c, 0xa9, 0x35, 0x65, 0x01, 0xba, 0x18, 0x65, 0xf9, 0x06, 0xd9, 0xf2, 0xfc, 0xaa, 0x75,
	0x06, 0xd1, 0xf5, 0x14, 0x7b, 0xc5, 0x18, 0x0c, 0xd6, 0xca, 0x1d, 0x89, 0x5f, 0x21, 0xa8, 0xf6,
	0x59, 0xad, 0x93, 0x2e, 0x72, 0x0b, 0x82, 0x4d, 0x20, 0xfd, 0x56, 0xba, 0xc7, 0xe5, 0xcb, 0x59,
	0x06, 0xc3, 0xa7, 0x56, 0xbb, 0xe3, 0xe2, 0x01, 0xf2, 0x18, 0x99, 0x55, 0x17, 0xf5, 0xe4, 0x2f,
	0x8d, 0x12, 0xa8, 0x43, 0xae, 0xd5, 0x88, 0x52, 0xdd, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa6,
	0x92, 0xfe, 0x6b, 0x29, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisterClient is the client API for Register service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Empty, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Register/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterServer is the server API for Register service.
type RegisterServer interface {
	Register(context.Context, *RegisterReq) (*Empty, error)
}

// UnimplementedRegisterServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterServer struct {
}

func (*UnimplementedRegisterServer) Register(ctx context.Context, req *RegisterReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Register/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Register_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "register.proto",
}
