// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_SUCCESS                                       Status = 0
	Status_FAIL                                          Status = 1
	Status_BLOCKED                                       Status = 2
	Status_DELETED                                       Status = 3
	Status_CREATED                                       Status = 4
	Status_TIMEOUT                                       Status = 5
	Status_ERROR                                         Status = 6
	Status_NOTFOUND                                      Status = 7
	Status_INVALID_PASSWORD                              Status = 8
	Status_INVALID_FIRSTNAME                             Status = 9
	Status_INVALID_LASTNAME                              Status = 10
	Status_INVALID_EMAIL                                 Status = 11
	Status_INVALID_PHONE                                 Status = 12
	Status_INVALID_ADRESS                                Status = 13
	Status_INVALID_DEVICE                                Status = 14
	Status_INVALID_USERNAME                              Status = 15
	Status_VALIDATED                                     Status = 16
	Status_EXITSTS                                       Status = 17
	Status_MAXIMUN_NUMBER_OF_USERS_REACHED               Status = 18
	Status_NOAUTH                                        Status = 19
	Status_MAXIMUN_NUMBER_OF_TOPICS_REACHED              Status = 20
	Status_MAXIMUN_NUMBER_OF_MESSAGES_PEER_TOPIC_REACHED Status = 21
	Status_NEW                                           Status = 22
	Status_INVALID_APPNAME                               Status = 23
	Status_INVALID_TOKEN                                 Status = 24
)

var Status_name = map[int32]string{
	0:  "SUCCESS",
	1:  "FAIL",
	2:  "BLOCKED",
	3:  "DELETED",
	4:  "CREATED",
	5:  "TIMEOUT",
	6:  "ERROR",
	7:  "NOTFOUND",
	8:  "INVALID_PASSWORD",
	9:  "INVALID_FIRSTNAME",
	10: "INVALID_LASTNAME",
	11: "INVALID_EMAIL",
	12: "INVALID_PHONE",
	13: "INVALID_ADRESS",
	14: "INVALID_DEVICE",
	15: "INVALID_USERNAME",
	16: "VALIDATED",
	17: "EXITSTS",
	18: "MAXIMUN_NUMBER_OF_USERS_REACHED",
	19: "NOAUTH",
	20: "MAXIMUN_NUMBER_OF_TOPICS_REACHED",
	21: "MAXIMUN_NUMBER_OF_MESSAGES_PEER_TOPIC_REACHED",
	22: "NEW",
	23: "INVALID_APPNAME",
	24: "INVALID_TOKEN",
}

var Status_value = map[string]int32{
	"SUCCESS":                          0,
	"FAIL":                             1,
	"BLOCKED":                          2,
	"DELETED":                          3,
	"CREATED":                          4,
	"TIMEOUT":                          5,
	"ERROR":                            6,
	"NOTFOUND":                         7,
	"INVALID_PASSWORD":                 8,
	"INVALID_FIRSTNAME":                9,
	"INVALID_LASTNAME":                 10,
	"INVALID_EMAIL":                    11,
	"INVALID_PHONE":                    12,
	"INVALID_ADRESS":                   13,
	"INVALID_DEVICE":                   14,
	"INVALID_USERNAME":                 15,
	"VALIDATED":                        16,
	"EXITSTS":                          17,
	"MAXIMUN_NUMBER_OF_USERS_REACHED":  18,
	"NOAUTH":                           19,
	"MAXIMUN_NUMBER_OF_TOPICS_REACHED": 20,
	"MAXIMUN_NUMBER_OF_MESSAGES_PEER_TOPIC_REACHED": 21,
	"NEW":             22,
	"INVALID_APPNAME": 23,
	"INVALID_TOKEN":   24,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("api.Status", Status_name, Status_value)
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_dfe4fce6682daf5b) }

var fileDescriptor_dfe4fce6682daf5b = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcd, 0xae, 0xd3, 0x30,
	0x10, 0x85, 0x81, 0xb4, 0x49, 0x3b, 0xfd, 0x9b, 0x4e, 0x5b, 0x60, 0x07, 0x02, 0x56, 0x48, 0x20,
	0x21, 0x9e, 0xc0, 0x8d, 0x27, 0xd4, 0x6a, 0x62, 0x47, 0xb6, 0xd3, 0x76, 0x17, 0x95, 0x1d, 0x0b,
	0xd4, 0x8a, 0x86, 0x05, 0xaf, 0xcc, 0x53, 0x5c, 0x39, 0xf7, 0xb6, 0x37, 0x52, 0x97, 0xe7, 0xf3,
	0x1c, 0x8d, 0x3f, 0xcb, 0x30, 0xbe, 0x34, 0xc7, 0xe6, 0xef, 0xe5, 0xeb, 0xf9, 0xcf, 0xa9, 0x39,
	0x51, 0x74, 0x3c, 0xff, 0xfa, 0x90, 0x40, 0x9f, 0x7f, 0x9f, 0x9b, 0x7f, 0x9f, 0xff, 0x47, 0x10,
	0xbb, 0xf6, 0x98, 0x46, 0x90, 0xb8, 0x2a, 0x4d, 0xd9, 0x39, 0x7c, 0x41, 0x03, 0xe8, 0x65, 0x42,
	0xe5, 0xf8, 0x32, 0xe0, 0x75, 0x6e, 0xd2, 0x2d, 0x4b, 0x7c, 0x15, 0x82, 0xe4, 0x9c, 0x3d, 0x4b,
	0x8c, 0x42, 0x48, 0x2d, 0x8b, 0x10, 0x7a, 0x21, 0x78, 0x55, 0xb0, 0xa9, 0x3c, 0xf6, 0x69, 0x08,
	0x7d, 0xb6, 0xd6, 0x58, 0x8c, 0x69, 0x0c, 0x03, 0x6d, 0x7c, 0x66, 0x2a, 0x2d, 0x31, 0xa1, 0x25,
	0xa0, 0xd2, 0x3b, 0x91, 0x2b, 0x59, 0x97, 0xc2, 0xb9, 0xbd, 0xb1, 0x12, 0x07, 0xb4, 0x82, 0xf9,
	0x95, 0x66, 0xca, 0x3a, 0xaf, 0x45, 0xc1, 0x38, 0xec, 0x0e, 0xe7, 0xe2, 0x89, 0x02, 0xcd, 0x61,
	0x72, 0xa5, 0x5c, 0x84, 0x2b, 0x8e, 0xba, 0xa8, 0xdc, 0x18, 0xcd, 0x38, 0x26, 0x82, 0xe9, 0x15,
	0x09, 0x69, 0x83, 0xd3, 0xa4, 0xcb, 0x24, 0xef, 0x54, 0xca, 0x38, 0xed, 0xee, 0xa8, 0x1c, 0xdb,
	0x76, 0xc7, 0x8c, 0x26, 0x30, 0x6c, 0x59, 0xeb, 0x86, 0xc1, 0x8d, 0x0f, 0xca, 0x3b, 0xef, 0x70,
	0x4e, 0x1f, 0xe1, 0x5d, 0x21, 0x0e, 0xaa, 0xa8, 0x74, 0xad, 0xab, 0x62, 0xcd, 0xb6, 0x36, 0x59,
	0xdb, 0x75, 0xb5, 0x65, 0x91, 0x6e, 0x58, 0x22, 0x11, 0x40, 0xac, 0x8d, 0xa8, 0xfc, 0x06, 0x17,
	0xf4, 0x09, 0xde, 0xdf, 0x17, 0xbc, 0x29, 0x55, 0xfa, 0xdc, 0x58, 0xd2, 0x37, 0xf8, 0x72, 0x3f,
	0x55, 0xb0, 0x73, 0xe2, 0x07, 0xbb, 0xba, 0x64, 0xb6, 0x8f, 0x9d, 0x5b, 0x65, 0x45, 0x09, 0x44,
	0x9a, 0xf7, 0xf8, 0x9a, 0x16, 0x30, 0xbb, 0xc9, 0x96, 0x65, 0xeb, 0xf0, 0xa6, 0xfb, 0x28, 0xde,
	0x6c, 0x59, 0xe3, 0xdb, 0x9f, 0x71, 0xfb, 0x03, 0xbe, 0x3f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1f,
	0xc8, 0x82, 0xc0, 0x11, 0x02, 0x00, 0x00,
}
