// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topics.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Topic struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=api.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_72af2b0eeeefc419, []int{0}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Topic) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Topic) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESS
}

type Topics struct {
	List                 []*Topic `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topics) Reset()         { *m = Topics{} }
func (m *Topics) String() string { return proto.CompactTextString(m) }
func (*Topics) ProtoMessage()    {}
func (*Topics) Descriptor() ([]byte, []int) {
	return fileDescriptor_72af2b0eeeefc419, []int{1}
}

func (m *Topics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topics.Unmarshal(m, b)
}
func (m *Topics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topics.Marshal(b, m, deterministic)
}
func (m *Topics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topics.Merge(m, src)
}
func (m *Topics) XXX_Size() int {
	return xxx_messageInfo_Topics.Size(m)
}
func (m *Topics) XXX_DiscardUnknown() {
	xxx_messageInfo_Topics.DiscardUnknown(m)
}

var xxx_messageInfo_Topics proto.InternalMessageInfo

func (m *Topics) GetList() []*Topic {
	if m != nil {
		return m.List
	}
	return nil
}

type TopicReq struct {
	List                 *Topics  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicReq) Reset()         { *m = TopicReq{} }
func (m *TopicReq) String() string { return proto.CompactTextString(m) }
func (*TopicReq) ProtoMessage()    {}
func (*TopicReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_72af2b0eeeefc419, []int{2}
}

func (m *TopicReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicReq.Unmarshal(m, b)
}
func (m *TopicReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicReq.Marshal(b, m, deterministic)
}
func (m *TopicReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicReq.Merge(m, src)
}
func (m *TopicReq) XXX_Size() int {
	return xxx_messageInfo_TopicReq.Size(m)
}
func (m *TopicReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicReq.DiscardUnknown(m)
}

var xxx_messageInfo_TopicReq proto.InternalMessageInfo

func (m *TopicReq) GetList() *Topics {
	if m != nil {
		return m.List
	}
	return nil
}

type TopicResp struct {
	List                 *Topics  `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicResp) Reset()         { *m = TopicResp{} }
func (m *TopicResp) String() string { return proto.CompactTextString(m) }
func (*TopicResp) ProtoMessage()    {}
func (*TopicResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_72af2b0eeeefc419, []int{3}
}

func (m *TopicResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicResp.Unmarshal(m, b)
}
func (m *TopicResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicResp.Marshal(b, m, deterministic)
}
func (m *TopicResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicResp.Merge(m, src)
}
func (m *TopicResp) XXX_Size() int {
	return xxx_messageInfo_TopicResp.Size(m)
}
func (m *TopicResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicResp.DiscardUnknown(m)
}

var xxx_messageInfo_TopicResp proto.InternalMessageInfo

func (m *TopicResp) GetList() *Topics {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Topic)(nil), "api.Topic")
	proto.RegisterType((*Topics)(nil), "api.Topics")
	proto.RegisterType((*TopicReq)(nil), "api.TopicReq")
	proto.RegisterType((*TopicResp)(nil), "api.TopicResp")
}

func init() { proto.RegisterFile("topics.proto", fileDescriptor_72af2b0eeeefc419) }

var fileDescriptor_72af2b0eeeefc419 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x98, 0x46, 0xf4, 0xd2, 0x46, 0xe8, 0xa6, 0x28, 0x03, 0x44, 0x01, 0x21, 0x4b,
	0xa0, 0x0c, 0xe1, 0x19, 0x58, 0x19, 0x52, 0x5e, 0x20, 0x69, 0xa3, 0xea, 0x24, 0x68, 0xdc, 0xdc,
	0x79, 0x60, 0xe4, 0xcd, 0x51, 0x6d, 0x0b, 0x55, 0x2c, 0x74, 0xf3, 0xff, 0xdf, 0xe7, 0x4f, 0x67,
	0xc3, 0x4a, 0x26, 0x4b, 0x5b, 0x6e, 0xec, 0x3c, 0xc9, 0x84, 0xba, 0xb7, 0x54, 0xae, 0x58, 0x7a,
	0x71, 0xb1, 0x2a, 0xf3, 0x79, 0xdc, 0x13, 0xcb, 0x38, 0x87, 0x5c, 0xbf, 0xc1, 0xe2, 0xfd, 0x74,
	0x05, 0x73, 0x48, 0x68, 0x57, 0xa8, 0x4a, 0x99, 0x65, 0x97, 0xd0, 0x0e, 0x6f, 0x40, 0x4b, 0xbf,
	0x2f, 0x12, 0x5f, 0x9c, 0x8e, 0x78, 0x0f, 0x69, 0x50, 0x15, 0xba, 0x52, 0x26, 0x6f, 0xb3, 0xa6,
	0xb7, 0xd4, 0x6c, 0x7c, 0xd5, 0xc5, 0x51, 0x6d, 0x20, 0xf5, 0x3e, 0xc6, 0x5b, 0xb8, 0xfa, 0x20,
	0x96, 0x42, 0x55, 0xda, 0x64, 0x2d, 0x78, 0xd8, 0x8f, 0x3a, 0xdf, 0xd7, 0x4f, 0x70, 0x1d, 0xe2,
	0x78, 0xc4, 0xbb, 0x5f, 0x56, 0x99, 0x2c, 0x8a, 0x83, 0x26, 0xc2, 0xcf, 0xb0, 0x8c, 0x30, 0xdb,
	0x7f, 0xe9, 0xf6, 0x5b, 0xc1, 0x7a, 0xe3, 0x06, 0xde, 0xce, 0x64, 0x85, 0xa6, 0x03, 0xe3, 0x03,
	0x68, 0x76, 0x03, 0xae, 0xcf, 0xb6, 0x18, 0x8f, 0x65, 0x7e, 0x1e, 0xd9, 0xe2, 0x23, 0x2c, 0xdc,
	0xe1, 0x02, 0xae, 0x0e, 0x0b, 0x60, 0x78, 0xd4, 0xeb, 0xa7, 0x95, 0xaf, 0xbf, 0xcc, 0x90, 0xfa,
	0xff, 0x7d, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xab, 0x26, 0xe3, 0x8f, 0x92, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubscriptionsClient is the client API for Subscriptions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubscriptionsClient interface {
	Sub(ctx context.Context, in *TopicReq, opts ...grpc.CallOption) (*TopicResp, error)
	Unsub(ctx context.Context, in *TopicReq, opts ...grpc.CallOption) (*TopicResp, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicResp, error)
}

type subscriptionsClient struct {
	cc *grpc.ClientConn
}

func NewSubscriptionsClient(cc *grpc.ClientConn) SubscriptionsClient {
	return &subscriptionsClient{cc}
}

func (c *subscriptionsClient) Sub(ctx context.Context, in *TopicReq, opts ...grpc.CallOption) (*TopicResp, error) {
	out := new(TopicResp)
	err := c.cc.Invoke(ctx, "/api.Subscriptions/sub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) Unsub(ctx context.Context, in *TopicReq, opts ...grpc.CallOption) (*TopicResp, error) {
	out := new(TopicResp)
	err := c.cc.Invoke(ctx, "/api.Subscriptions/unsub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionsClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TopicResp, error) {
	out := new(TopicResp)
	err := c.cc.Invoke(ctx, "/api.Subscriptions/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionsServer is the server API for Subscriptions service.
type SubscriptionsServer interface {
	Sub(context.Context, *TopicReq) (*TopicResp, error)
	Unsub(context.Context, *TopicReq) (*TopicResp, error)
	List(context.Context, *Empty) (*TopicResp, error)
}

// UnimplementedSubscriptionsServer can be embedded to have forward compatible implementations.
type UnimplementedSubscriptionsServer struct {
}

func (*UnimplementedSubscriptionsServer) Sub(ctx context.Context, req *TopicReq) (*TopicResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sub not implemented")
}
func (*UnimplementedSubscriptionsServer) Unsub(ctx context.Context, req *TopicReq) (*TopicResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsub not implemented")
}
func (*UnimplementedSubscriptionsServer) List(ctx context.Context, req *Empty) (*TopicResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterSubscriptionsServer(s *grpc.Server, srv SubscriptionsServer) {
	s.RegisterService(&_Subscriptions_serviceDesc, srv)
}

func _Subscriptions_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Subscriptions/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Sub(ctx, req.(*TopicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_Unsub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).Unsub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Subscriptions/Unsub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).Unsub(ctx, req.(*TopicReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscriptions_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Subscriptions/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionsServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Subscriptions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Subscriptions",
	HandlerType: (*SubscriptionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sub",
			Handler:    _Subscriptions_Sub_Handler,
		},
		{
			MethodName: "unsub",
			Handler:    _Subscriptions_Unsub_Handler,
		},
		{
			MethodName: "list",
			Handler:    _Subscriptions_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topics.proto",
}
